spring:
  application:
    name: intuit-job-posting
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    generate-unique-name: false
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        dialect: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: true
    change-log: classpath:/changelog/db-changelog-master.yml
server:
    servlet:
      context-path: /intuit-job-posting
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
